#zuul:
#  prefix: /api
#  ignoredServices: '*'
#  routes:
#    mailstat-mbox-splitter: /splitter/**
#    mailstat-api-gateway: /gateway/**

server:
  port: 8080

# Internationalization
spring.messages.basename: messages/messages

spring:
  cloud:
    refresh: false
    gateway:
      routes:
        - id: mailstat-mbox-splitter
          uri: lb://mailstat-mbox-splitter
          predicates:
            - Path=/api/splitter/**
          filters:
            - StripPrefix=2
  zipkin:
    baseUrl: http://mailstat-tracing-server:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://mailstat-discovery-server:8761/eureka/
