server:
  port: 8088

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://mailstat-tracing-server:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://mailstat-discovery-server:8761/eureka/
