server:
  port: 8089

spring:
  cloud:
    refresh:
      enabled: false
  zipkin:
    baseUrl: http://mailstat-tracing-server:9411
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB
      file-size-threshold: 2GB
eureka:
  client:
    serviceUrl:
      defaultZone: http://mailstat-discovery-server:8761/eureka/
